import = [
    "~/.config/alacritty/themes/themes/zenburn.toml"
]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

#[colors.bright]
#black = "#444b6a"
#blue = "#7da6ff"
#cyan = "#0db9d7"
#green = "#b9f27c"
#magenta = "#bb9af7"
#red = "#ff7a93"
#white = "#acb0d0"
#yellow = "#ff9e64"
#
#[colors.normal]
#black = "#32344a"
#blue = "#7aa2f7"
#cyan = "#449dab"
#green = "#9ece6a"
#magenta = "#ad8ee6"
#red = "#f7768e"
#white = "#787c99"
#yellow = "#e0af68"
#
#[colors.primary]
#background = "#11121D"
#foreground = "#a9b1d6"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[mouse.bindings]]
action = "Paste"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "Paste"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mods = "Control"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-defterm", "-here", "-no-start", "-use-full-path", "-ucrt64", "-msys", "-mingw64", "-shell zsh.exe"]
program = 'C:\tools\msys64\msys2_shell.cmd'


[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 120
lines = 35 
